# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: farse-ruby-client 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "farse-ruby-client"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Alan deLevie", "Adam Alpern"]
  s.date = "2014-07-31"
  s.description = "A simple Ruby client for the parse.com REST API"
  s.email = "adelevie@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "OLD_README.md",
    "README.md",
    "Rakefile",
    "VERSION",
    "example.rb",
    "features.md",
    "lib/faraday/better_retry.rb",
    "lib/faraday/extended_parse_json.rb",
    "lib/faraday/get_method_override.rb",
    "lib/farse-ruby-client.rb",
    "lib/farse/batch.rb",
    "lib/farse/client.rb",
    "lib/farse/cloud.rb",
    "lib/farse/datatypes.rb",
    "lib/farse/error.rb",
    "lib/farse/installation.rb",
    "lib/farse/model.rb",
    "lib/farse/object.rb",
    "lib/farse/protocol.rb",
    "lib/farse/push.rb",
    "lib/farse/query.rb",
    "lib/farse/user.rb",
    "lib/farse/util.rb",
    "farse-ruby-client.gemspec",
  ]
  s.homepage = "http://github.com/scpr/parse-ruby-client"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A simple Ruby client for the Parse REST API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<faraday>, [">= 0"])
      s.add_runtime_dependency(%q<faraday_middleware>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, ["= 2.5.0"])
      s.add_development_dependency(%q<mocha>, ["= 0.12.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.5"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<webmock>, ["~> 1.9.0"])
      s.add_development_dependency(%q<vcr>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
    else
      s.add_dependency(%q<faraday>, [">= 0"])
      s.add_dependency(%q<faraday_middleware>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<test-unit>, ["= 2.5.0"])
      s.add_dependency(%q<mocha>, ["= 0.12.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.5"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<webmock>, ["~> 1.9.0"])
      s.add_dependency(%q<vcr>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
    end
  else
    s.add_dependency(%q<faraday>, [">= 0"])
    s.add_dependency(%q<faraday_middleware>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<test-unit>, ["= 2.5.0"])
    s.add_dependency(%q<mocha>, ["= 0.12.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.5"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<webmock>, ["~> 1.9.0"])
    s.add_dependency(%q<vcr>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
  end
end

